name: Build and Deploy quote app

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Asegúrate de que esta versión coincida con tu entorno de desarrollo

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.APP_QUOTE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST25 }}
          SSH_USER: ${{ secrets.USER25 }}
          REMOTE_PATH: ${{ secrets.USER25 }}
          SSH_PORT: ${{ secrets.SSH_HOST25 }}
        run: |
          ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
          rsync -avz -e "ssh -p $SSH_PORT" --delete-after build/ $SSH_USER@$SSH_HOST:$REMOTE_PATH